# -*- coding: utf-8 -*-
"""employee_analysis.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1BvCY_HO9tXQZtPt8UxA_FUE4ilv5CivM

# **Loading the data**
"""

#!gdown 1sNNnoQApDF2TZZ16NmeduLEXC7aJwZpT

#!gdown 1-x_MO_L7Eu4qb2f7vQvcm3pq5NRGQXow

#!gdown 17ClKZVkwN9i-0A7Z2aXO-ozDtuO-_qq2

import numpy as np

import pandas as pd

employees = pd.read_csv('employees.csv', parse_dates=['join_date'])
salaries = pd.read_csv('salaries.csv', parse_dates=['effective_date'])
performance = pd.read_csv('performance.csv')

df = employees.merge(salaries, on='employee_id').merge(performance, on='employee_id')

# Add experience in years
df['experience_years'] = (pd.Timestamp.today() - df['join_date']).dt.days // 365

print(df.head())
print(df.info())
print(df.describe())

df.to_csv("merged.csv", index=False)

# 1. Average salary per department
avg_salary = df.groupby('department')['salary'].mean().reset_index()

# 2. Top performers
top_performers = df[df['performance_rating'] > 4.5]

# 3. Correlation
correlation = df[['salary', 'experience_years', 'performance_rating']].corr()

pip install streamlit matplotlib seaborn pandas

import seaborn as sns
import matplotlib.pyplot as plt
import streamlit as st

st.title("📊 Employee Data Analysis Dashboard")

# Show merged data
st.subheader("📋 Merged Data")
st.dataframe(df)

# Show average salary
st.subheader("💰 Average Salary by Department")
st.dataframe(avg_salary)

# Visual 1: Boxplot - Salary by Department
st.subheader("📦 Salary Distribution by Department")
fig1, ax1 = plt.subplots()
sns.boxplot(x='department', y='salary', data=df, ax=ax1)
st.pyplot(fig1)

# Visual 2: Scatterplot - Performance vs Salary
st.subheader("📈 Performance vs Salary")
fig2, ax2 = plt.subplots()
sns.scatterplot(x='performance_rating', y='salary', hue='department', data=df, ax=ax2)
st.pyplot(fig2)

# Visual 3: Correlation Heatmap
st.subheader("📊 Correlation Heatmap")
fig3, ax3 = plt.subplots()
sns.heatmap(correlation, annot=True, cmap="coolwarm", ax=ax3)
st.pyplot(fig3)





